controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_welcome:
    path: /welcome
    controller: App\Controller\HomeController::welcome
app_home:
    path: /home
    controller: App\Controller\HomeController::index
app_name:
    path: /name/{name}/{age}
    controller: App\Controller\HomeController::name
    requirements:
        name: '[a-zA-Z]+'
        age: '\d+'